/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aNew.thread;

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {
  @Test
  public void threadDemoTest() {
    NewThread classUnderTest = new NewThread();
    assertNotNull("Demo Thread", classUnderTest.t);
  }
}
